// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsde-6QTTa-wIcEUJNvbyyw5JYrOnLLxI',
    appId: '1:3768392019:web:357aacb8ca96260b0e29a6',
    messagingSenderId: '3768392019',
    projectId: 'foodapp-a18c3',
    authDomain: 'foodapp-a18c3.firebaseapp.com',
    storageBucket: 'foodapp-a18c3.appspot.com',
    measurementId: 'G-2P9EC7B9ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0pxS2rPZTiEVnSYL1cpKpgeMwDnYPYGo',
    appId: '1:3768392019:android:6ebf6564add924210e29a6',
    messagingSenderId: '3768392019',
    projectId: 'foodapp-a18c3',
    storageBucket: 'foodapp-a18c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-73OV-OVQWv0o7x75FKCgH6goiDE-eeY',
    appId: '1:3768392019:ios:c6017ef15747e5890e29a6',
    messagingSenderId: '3768392019',
    projectId: 'foodapp-a18c3',
    storageBucket: 'foodapp-a18c3.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-73OV-OVQWv0o7x75FKCgH6goiDE-eeY',
    appId: '1:3768392019:ios:623636e07c9efd0f0e29a6',
    messagingSenderId: '3768392019',
    projectId: 'foodapp-a18c3',
    storageBucket: 'foodapp-a18c3.appspot.com',
    iosBundleId: 'com.example.foodApp.RunnerTests',
  );
}
